# Generated by Django 5.2.5 on 2025-08-28 14:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_date", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField()),
                ("image_url", models.URLField(max_length=300)),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "comments",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("read_more_link", models.URLField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["published_date"], name="core_articl_publish_46fd58_idx"
                    ),
                    models.Index(
                        fields=["author"], name="core_articl_author__e61453_idx"
                    ),
                    models.Index(fields=["views"], name="core_articl_views_6437fa_idx"),
                ],
            },
        ),
    ]
