# Generated by Django 5.2.5 on 2025-08-28 15:50

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["date", "created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="core_articl_publish_46fd58_idx",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="published_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="image_url",
            new_name="image",
        ),
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["date"], name="core_articl_date_304ab3_idx"),
        ),
    ]
