# Generated by Django 5.2.5 on 2025-08-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_article_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="read_more_link",
            new_name="readMore",
        ),
    ]
