# Generated by Django 5.2.5 on 2025-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_read_more_link_article_readmore"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="article",
            new_name="core_articl_author_0f51e2_idx",
            old_name="core_articl_author__e61453_idx",
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(max_length=250),
        ),
    ]
