# Generated by Django 5.2.5 on 2025-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0004_rename_core_articl_author__e61453_idx_core_articl_author_0f51e2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="readMore",
            field=models.URLField(default="#", max_length=300),
        ),
    ]
