# Generated by Django 5.2.5 on 2025-08-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_article_readmore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-date", "created_at"]},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="readMore",
            new_name="read_more",
        ),
    ]
