# Generated by Django 5.2.5 on 2025-08-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_article_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="core_articl_author_0f51e2_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="core_articl_views_6437fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="core_articl_date_304ab3_idx",
        ),
    ]
