# Generated by Django 5.2.5 on 2025-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_article_core_articl_author_0f51e2_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="read_more",
            field=models.URLField(blank=True, default="#", max_length=300),
        ),
    ]
