# Generated by Django 5.2.5 on 2025-08-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_article_read_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="read_more",
            field=models.CharField(blank=True, default="#", max_length=300),
        ),
    ]
